# Generated by Django 5.1.2 on 2024-10-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='privacy_settings',
        ),
    ]
