# Generated by Django 5.1.2 on 2024-10-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentAPI', '0002_remove_user_privacy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desired_salary_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_job_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_job_type',
            field=models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote')], default='On-site', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
