# Generated by Django 5.1.2 on 2024-10-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentAPI', '0003_user_desired_salary_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recent_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
