# Generated by Django 5.1.3 on 2024-11-28 17:51

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitmentAPI', '0014_alter_post_options_comment_likes_count_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='recruitment_created_b1f62c_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='recruitment_user_id_1cb275_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='attachment',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('both', 'Both'), ('none', 'None')], default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['-created_at'], name='recruitment_created_064d48_btree'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', '-created_at'], name='recruitment_user_id_0ba3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_active', 'is_hidden', '-created_at'], name='recruitment_is_acti_c82953_idx'),
        ),
    ]
